-- MyDSL learned creaturelore DB. Auto-generated.
-- Safe to back up. Edit only while Mudlet is closed.
return {
  lothaw = {
    source = "scan",
    lastSeen = 1780791192,
    aliases = {
      lothaw = true,
    },
    roomsFound = {
      ["unknown room"] = 20,
      ["Palace Courtyard"] = 5,
    },
    lastSeenRoomName = "unknown room",
    scan = {
      raw = "Lothaw, right here.",
      name = "Lothaw",
      count = 1,
      display = "Lothaw",
      updated = 1780788422,
      where = "right here",
      key = "lothaw",
    },
    updated = 1780788422,
    lastSeenWhere = "right here",
    name = "Lothaw",
    key = "lothaw",
    display = "Lothaw",
    lastSeenAt = 1780791192,
    lastSeenArea = "unknown area",
    lastScanLocation = "right here",
  },
  ["gnome machinist"] = {
    lastXP = 86,
    tactics = "bash trip",
    lastSeen = 1780152234,
    magic = 1039,
    lastKilledArea = "unknown area",
    xpTotal = 86,
    key = "gnome machinist",
    affects = "haste",
    alignmentText = "a good",
    killLocations = {
      ["Northeast end of the Clockworks"] = 2,
    },
    _lastKillToken = 1779694982.447,
    killCount = 1,
    lastSeenArea = "unknown area",
    name = "a gnome machinist",
    resistances = "mental disease",
    display = "a gnome machinist",
    lastSeenRoomName = "unknown room",
    silver = 0,
    lastSeenAt = 1780152234,
    sex = "male",
    roomsFound = {
      ["Northeast end of the Clockworks"] = 240,
      ["Eastern end of the Clockworks"] = 95,
      ["unknown room"] = 306,
      ["The Docks"] = 16,
      ["Northern end of the Clockworks"] = 14,
    },
    hp = 3631,
    coins = {
      silver = 0,
      gold = 0,
    },
    updated = 1779686122,
    _lastXPSampleToken = 1779694982.447,
    level = "47",
    gold = 0,
    xpSamples = 1,
    lastSeenWhere = "right here",
    source = "scan",
    lastScanLocation = "right here",
    dmg = "6d6 slash",
    damageType = "slash",
    lastKilledAt = 1779694982.447,
    damage = "6d6 slash",
    lastLore = 1779686122.139,
    lored = true,
    baseMana = 1039,
    scan = {
      raw = "a gnome machinist, nearby to the southwest.",
      name = "a gnome machinist",
      count = 4,
      display = "a gnome machinist",
      updated = 1779693787,
      where = "the southwest.",
      key = "gnome machinist",
    },
    resist = "mental disease",
    avgXP = 86,
    lastKilledRoomName = "Northeast end of the Clockworks",
    rawLore = {
      [13] = "This creature is affected by haste",
      [7] = "The base magically ability of this creature is 1039.",
      [1] = "Creature: a gnome machinist Race: tinker gnome",
      [2] = "----------------------------------------------------------",
      [4] = "Their wealth appears to be 0 gold and 0 silver",
      [8] = "This creature is upon the cycle of training '47'",
      [9] = "This creature does 6d6 damage in a slash manner.",
      [5] = "They appear to be male.",
      [10] = "The creature has the following characteristics:",
      [14] = "",
      [3] = "a gnome machinist appears to be a good soul.",
      [6] = "The base health of this creature is 3631.",
      [12] = "Resistances: mental disease",
      [11] = "Offensive Tactics:bash trip",
    },
    aliases = {
      ["gnome machinist"] = true,
      machinist = true,
    },
    race = "tinker gnome",
    resists = "mental disease",
    baseHp = 3631,
  },
  ["gnome philosopher's assistant"] = {
    dmg = "6d7 slap",
    tactics = "bash trip",
    source = "creaturelore",
    learnedAt = 1779689497,
    aliases = {
      ["gnome philosopher s assistant"] = true,
      ["gnome philosopher's assistant"] = true,
      ["gnome philosophers assistant"] = true,
      ["philosopher's assistant"] = true,
      assistant = true,
    },
    updated = 1779692215,
    race = "tinker gnome",
    loreSource = "learned",
    commandKey = "'gnome philosopher s assistant'",
    level = "52",
    vulnerabilities = "fire",
    damage = "6d7 slap",
    baseMana = 1212,
    resist = "mental disease",
    key = "gnome philosopher's assistant",
    lastUpdated = 1779692215,
    resistances = "mental disease",
    display = "a gnome philosopher's assistant",
    baseHp = 5749,
    magic = 1212,
    name = "a gnome philosopher's assistant",
  },
  falconer = {
    source = "scan",
    lastSeen = 1780791192,
    aliases = {
      falconer = true,
    },
    roomsFound = {
      ["Palace Courtyard"] = 7,
      ["Center of the Courtyard"] = 1,
      ["unknown room"] = 28,
    },
    lastSeenRoomName = "unknown room",
    scan = {
      raw = "a falconer, right here.",
      name = "a falconer",
      count = 1,
      display = "a falconer",
      updated = 1780788207,
      where = "right here",
      key = "falconer",
    },
    updated = 1780788207,
    lastSeenWhere = "right here",
    name = "a falconer",
    key = "falconer",
    display = "a falconer",
    lastSeenAt = 1780791192,
    lastSeenArea = "unknown area",
    lastScanLocation = "right here",
  },
  zecnys = {
    source = "scan",
    lastSeen = 1780791192,
    updated = 1780788207,
    key = "zecnys",
    lastSeenRoomName = "unknown room",
    aliases = {
      zecnys = true,
    },
    roomsFound = {
      ["Palace Courtyard"] = 7,
      Limbo = 3,
      ["unknown room"] = 28,
      ["Center of the Courtyard"] = 1,
    },
    lastSeenWhere = "right here",
    name = "Zecnys",
    scan = {
      raw = "Zecnys, right here.",
      name = "Zecnys",
      count = 1,
      display = "Zecnys",
      updated = 1780788207,
      where = "right here",
      key = "zecnys",
    },
    display = "Zecnys",
    lastSeenAt = 1780791192,
    lastSeenArea = "unknown area",
    lastScanLocation = "right here",
  },
  kayla = {
    source = "scan",
    lastSeen = 1780791192,
    aliases = {
      kayla = true,
    },
    roomsFound = {
      ["Palace Courtyard"] = 7,
      ["Center of the Courtyard"] = 1,
      ["unknown room"] = 28,
    },
    lastSeenRoomName = "unknown room",
    scan = {
      raw = "Kayla, right here.",
      name = "Kayla",
      count = 1,
      display = "Kayla",
      updated = 1780788207,
      where = "right here",
      key = "kayla",
    },
    updated = 1780788207,
    lastSeenWhere = "right here",
    name = "Kayla",
    key = "kayla",
    display = "Kayla",
    lastSeenAt = 1780791192,
    lastSeenArea = "unknown area",
    lastScanLocation = "right here",
  },
  geirhart = {
    source = "scan",
    lastSeen = 1780791192,
    scan = {
      raw = "Geirhart, right here.",
      name = "Geirhart",
      count = 1,
      display = "Geirhart",
      updated = 1780788255,
      where = "right here",
      key = "geirhart",
    },
    roomsFound = {
      ["The Hill-lands"] = 2,
      ["unknown room"] = 24,
      ["Rolling forest"] = 1,
      Limbo = 4,
      ["A Trail Around Shalonesti"] = 2,
      ["Palace Courtyard"] = 6,
    },
    lastSeenRoomName = "unknown room",
    aliases = {
      geirhart = true,
    },
    lastSeenArea = "unknown area",
    lastSeenWhere = "right here",
    name = "Geirhart",
    key = "geirhart",
    display = "Geirhart",
    lastSeenAt = 1780791192,
    updated = 1780788255,
    lastScanLocation = "right here",
  },
  waitress = {
    aliases = {
      waitress = true,
    },
    source = "scan",
    lastSeen = 1780151325,
    lastSeenArea = "unknown area",
    rooms = {
      ["In the Main Gathering Room of the Fellowship Saloon"] = 3,
    },
    lastSeenAt = 1780151325,
    scan = {
      raw = "a waitress, right here.",
      name = "a waitress",
      key = "waitress",
      display = "a waitress",
      where = "right here",
      updated = 1780151325,
      count = 1,
    },
    roomsFound = {
      ["In the Main Gathering Room of the Fellowship Saloon"] = 9,
      ["Chamber of the High Priest of Althainia"] = 1,
      ["unknown room"] = 4,
      ["Market Square"] = 1,
      ["A Quiet bar in the Blue Gryphon"] = 1,
      ["Common Room of the Blue Gryphon"] = 28,
      ["The Altar Room"] = 3,
      ["Northeast end of the Clockworks"] = 3,
    },
    lastSeenWhere = "right here",
    name = "a waitress",
    key = "waitress",
    display = "a waitress",
    lastSeenRoomName = "unknown room",
    updated = 1780151325,
    lastScanLocation = "right here",
  },
  ["hill dwarven prospector"] = {
    source = "scan",
    lastSeen = 1780792807,
    aliases = {
      ["hill dwarven prospector"] = true,
      ["dwarven prospector"] = true,
      prospector = true,
    },
    updated = 1780606633,
    lastSeenWhere = "right here",
    key = "hill dwarven prospector",
    killLocations = {
      ["The Hill-lands"] = 2,
    },
    lastScanLocation = "right here",
    lastKilledAt = 1780698410.539,
    drops = {
      ["short dagger"] = 1,
    },
    _lastKillToken = 1780698410.539,
    lastKilledArea = "unknown area",
    killCount = 1,
    scan = {
      raw = "a hill dwarven prospector, nearby to the northeast.",
      name = "a hill dwarven prospector",
      count = 8,
      display = "a hill dwarven prospector",
      updated = 1780606633,
      where = "the northeast.",
      key = "hill dwarven prospector",
    },
    roomsFound = {
      ["unknown room"] = 20,
      ["The Hill-lands"] = 55,
    },
    name = "a hill dwarven prospector",
    lastKilledRoomName = "The Hill-lands",
    lastSeenAt = 1780792807,
    display = "a hill dwarven prospector",
    lastSeenRoomName = "unknown room",
    coins = {
      silver = 0,
      gold = 0,
    },
    lastSeenArea = "unknown area",
  },
  ["wild wolf"] = {
    scan = {
      raw = "a wild wolf, right here.",
      name = "a wild wolf",
      count = 1,
      display = "a wild wolf",
      updated = 1779740545,
      where = "right here",
      key = "wild wolf",
    },
    source = "scan",
    lastSeen = 1779741824,
    group = {
      raw = "[51 Mob] A wild wolf      100% hp   0% mana 100% mv",
      manaPct = 0,
      key = "wild wolf",
      movePct = 100,
      hpPct = 100,
      level = 51,
      class = "Mob",
      name = "A wild wolf",
    },
    updated = 1779740545,
    lastSeenAt = 1779741824,
    aliases = {
      ["wild wolf"] = true,
      wolf = true,
    },
    lastSeenArea = "unknown area",
    lastSeenWhere = "right here",
    name = "a wild wolf",
    key = "wild wolf",
    display = "a wild wolf",
    lastSeenRoomName = "unknown room",
    roomsFound = {
      ["Eastern end of the Clockworks"] = 6,
      ["unknown room"] = 24,
    },
    lastScanLocation = "right here",
  },
  ["insane sea elf"] = {
    lastXP = 3998,
    avgXP = 2109,
    lastSeen = 1779756480,
    xpSamples = 2,
    aliases = {
      ["insane sea elf"] = true,
      ["sea elf"] = true,
      elf = true,
    },
    updated = 1779731311,
    lastSeenWhere = "right here",
    key = "insane sea elf",
    xpTotal = 4218,
    killLocations = {
      ["A Room"] = 16,
      ["City street"] = 34,
    },
    lastScanLocation = "right here",
    source = "scan",
    lastSeenRoomName = "unknown room",
    lastKilledAt = 1779754044.46,
    drops = {
      ["silver coin"] = 34,
    },
    _lastKillToken = 1779754044.46,
    lastSeenArea = "unknown area",
    killCount = 2,
    scan = {
      raw = "an insane sea elf, right here.",
      name = "an insane sea elf",
      key = "insane sea elf",
      display = "an insane sea elf",
      where = "right here",
      updated = 1779731311,
      count = 3,
    },
    roomsFound = {
      ["A Room"] = 10,
      ["unknown room"] = 36,
    },
    _lastXPSampleToken = 1779754044.46,
    name = "an insane sea elf",
    lastKilledRoomName = "City street",
    display = "an insane sea elf",
    lastSeenAt = 1779756480,
    coins = {
      silver = 0,
      gold = 0,
    },
    lastKilledArea = "unknown area",
  },
  ["dwarven mage"] = {
    source = "scan",
    lastSeen = 1779700143,
    scan = {
      raw = "a dwarven mage, nearby to the west.",
      name = "a dwarven mage",
      count = 6,
      display = "a dwarven mage",
      updated = 1779700143,
      where = "the west.",
      key = "dwarven mage",
    },
    roomsFound = {
      ["Entrance To The Camp"] = 2,
      ["unknown room"] = 4,
      ["Higher Ground  "] = 6,
    },
    lastSeenAt = 1779700143,
    aliases = {
      ["dwarven mage"] = true,
      mage = true,
    },
    lastSeenArea = "unknown area",
    lastSeenWhere = "right here",
    name = "a dwarven mage",
    key = "dwarven mage",
    display = "a dwarven mage",
    lastSeenRoomName = "unknown room",
    updated = 1779700143,
    lastScanLocation = "right here",
  },
  ["dwarven axe man"] = {
    source = "scan",
    lastSeen = 1779700113,
    scan = {
      raw = "a dwarven axe man, nearby to the west.",
      name = "a dwarven axe man",
      count = 6,
      display = "a dwarven axe man",
      updated = 1779700112,
      where = "the west.",
      key = "dwarven axe man",
    },
    roomsFound = {
      ["unknown room"] = 4,
      ["Entrance To The Camp"] = 6,
    },
    lastSeenAt = 1779700113,
    aliases = {
      ["dwarven axe man"] = true,
      man = true,
      ["axe man"] = true,
    },
    lastSeenArea = "unknown area",
    lastSeenWhere = "right here",
    name = "a dwarven axe man",
    key = "dwarven axe man",
    display = "a dwarven axe man",
    lastSeenRoomName = "unknown room",
    updated = 1779700112,
    lastScanLocation = "right here",
  },
  ["gnome factory worker"] = {
    lastXP = 38,
    lastSeen = 1780152234,
    xpSamples = 1,
    aliases = {
      ["gnome factory worker"] = true,
      ["factory worker"] = true,
      worker = true,
    },
    xpTotal = 44,
    key = "gnome factory worker",
    resists = "mental disease",
    level = "46",
    killLocations = {
      ["Northeast end of the Clockworks"] = 2,
    },
    _lastKillToken = 1779693858.137,
    baseHp = 3366,
    lastSeenArea = "unknown area",
    name = "a gnome factory worker",
    sex = "male",
    display = "a gnome factory worker",
    lastSeenAt = 1780152234,
    avgXP = 44,
    lastSeenRoomName = "unknown room",
    roomsFound = {
      ["Northeast end of the Clockworks"] = 242,
      ["Eastern end of the Clockworks"] = 93,
      ["unknown room"] = 310,
      ["The Docks"] = 16,
      ["Northern end of the Clockworks"] = 16,
    },
    hp = 3366,
    coins = {
      silver = 0,
      gold = 0,
    },
    updated = 1779686518,
    race = "tinker gnome",
    killCount = 1,
    gold = 0,
    _lastXPSampleToken = 1779695523.31,
    lastSeenWhere = "right here",
    magic = 1004,
    damage = "6d6 pound",
    lored = true,
    damageType = "pound",
    lastKilledAt = 1779693858.137,
    lastKilledArea = "unknown area",
    silver = 0,
    dmg = "6d6 pound",
    baseMana = 1004,
    scan = {
      raw = "a gnome factory worker, nearby to the southwest.",
      name = "a gnome factory worker",
      count = 4,
      display = "a gnome factory worker",
      updated = 1779693787,
      where = "the southwest.",
      key = "gnome factory worker",
    },
    resist = "mental disease",
    source = "scan",
    lastKilledRoomName = "Northeast end of the Clockworks",
    rawLore = {
      [7] = "The base magically ability of this creature is 1004.",
      [1] = "Creature: a gnome factory worker Race: tinker gnome",
      [2] = "----------------------------------------------------------",
      [4] = "Their wealth appears to be 0 gold and 0 silver",
      [8] = "This creature is upon the cycle of training '46'",
      [9] = "This creature does 6d6 damage in a pound manner.",
      [5] = "They appear to be male.",
      [10] = "The creature has the following characteristics:",
      [3] = "a gnome factory worker appears to be a good soul.",
      [6] = "The base health of this creature is 3366.",
      [12] = "",
      [11] = "Resistances: mental disease",
    },
    lastScanLocation = "right here",
    lastLore = 1779686518.484,
    alignmentText = "a good",
    resistances = "mental disease",
  },
  ["gnome student"] = {
    dmg = "5d8 pound",
    source = "creaturelore",
    learnedAt = 1779688285,
    aliases = {
      ["gnome student"] = true,
    },
    updated = 1779688285,
    race = "tinker gnome",
    loreSource = "learned",
    commandKey = "'gnome student'",
    level = "51",
    damage = "5d8 pound",
    baseMana = 1211,
    resist = "mental disease",
    lastUpdated = 1779688285,
    name = "a gnome student",
    resistances = "mental disease",
    display = "a gnome student",
    magic = 1211,
    baseHp = 5260,
    key = "gnome student",
  },
  ["chestnut mare"] = {
    dmg = "2d4 bite",
    lastSeen = 1779693160,
    magic = 104,
    aliases = {
      ["chestnut mare"] = true,
      mare = true,
    },
    key = "chestnut mare",
    lastLore = 1779692810.59,
    baseHp = 134,
    lastSeenArea = "unknown area",
    name = "a chestnut mare",
    sex = "female",
    display = "a chestnut mare",
    lastSeenRoomName = "unknown room",
    source = "creaturelore",
    hp = 134,
    updated = 1779692810,
    lastSeenWhere = "right here",
    commandKey = "'chestnut mare'",
    damage = "2d4 bite",
    lored = true,
    damageType = "bite",
    alignmentText = "a more neutral",
    lastScanLocation = "right here",
    silver = 0,
    level = "10",
    baseMana = 104,
    scan = {
      raw = "a chestnut mare, right here.",
      name = "a chestnut mare",
      count = 1,
      display = "a chestnut mare",
      updated = 1779692954,
      where = "right here",
      key = "chestnut mare",
    },
    race = "horse",
    learnedAt = 1779692810,
    lastUpdated = 1779692810,
    rawLore = {
      [7] = "The base magically ability of this creature is 104.",
      [1] = "Creature: a chestnut mare Race: horse",
      [2] = "----------------------------------------------------------",
      [4] = "Their wealth appears to be 0 gold and 0 silver",
      [8] = "This creature is upon the cycle of training '10'",
      [9] = "This creature does 2d4 damage in a bite manner.",
      [5] = "They appear to be female.",
      [10] = "The creature has the following characteristics:",
      [3] = "a chestnut mare appears to be a more neutral soul.",
      [6] = "The base health of this creature is 134.",
      [11] = "",
    },
    loreSource = "learned",
    gold = 0,
    roomsFound = {
      ["A Chainlink Platform in Fling-fall Cavern"] = 1,
      ["A Stone Slab Platform in Fling-fall Cavern"] = 2,
      ["unknown room"] = 10,
    },
    lastSeenAt = 1779693160,
  },
  ["insane half elf"] = {
    lastXP = 13336,
    avgXP = 2109,
    lastSeen = 1779756480,
    xpSamples = 2,
    aliases = {
      ["half elf"] = true,
      ["insane half elf"] = true,
      elf = true,
    },
    updated = 1779731311,
    lastSeenWhere = "right here",
    key = "insane half elf",
    xpTotal = 4218,
    killLocations = {
      ["A Room"] = 16,
      ["City street"] = 34,
    },
    lastScanLocation = "right here",
    source = "scan",
    lastSeenRoomName = "unknown room",
    lastKilledAt = 1779754044.46,
    drops = {
      ["silver coin"] = 34,
    },
    _lastKillToken = 1779754044.46,
    lastSeenArea = "unknown area",
    killCount = 2,
    scan = {
      raw = "an insane half elf, right here.",
      name = "an insane half elf",
      key = "insane half elf",
      display = "an insane half elf",
      where = "right here",
      updated = 1779731311,
      count = 3,
    },
    roomsFound = {
      ["A Room"] = 6,
      ["unknown room"] = 12,
    },
    _lastXPSampleToken = 1779754044.46,
    name = "an insane half elf",
    lastKilledRoomName = "City street",
    display = "an insane half elf",
    lastSeenAt = 1779756480,
    coins = {
      silver = 0,
      gold = 0,
    },
    lastKilledArea = "unknown area",
  },
  ["disfigured bear"] = {
    source = "scan",
    lastSeen = 1779700378,
    scan = {
      raw = "a disfigured bear, right here.",
      name = "a disfigured bear",
      count = 2,
      display = "a disfigured bear",
      updated = 1779700378,
      where = "right here",
      key = "disfigured bear",
    },
    roomsFound = {
      ["A Dim Forested Entrance"] = 2,
      ["unknown room"] = 4,
    },
    lastSeenAt = 1779700378,
    aliases = {
      ["disfigured bear"] = true,
      bear = true,
    },
    lastSeenArea = "unknown area",
    lastSeenWhere = "right here",
    name = "a disfigured bear",
    key = "disfigured bear",
    display = "a disfigured bear",
    lastSeenRoomName = "unknown room",
    updated = 1779700378,
    lastScanLocation = "right here",
  },
  ["mutated silver wolf"] = {
    lastXP = 4442,
    avgXP = 2898,
    lastSeen = 1780148900,
    xpSamples = 1,
    coins = {
      silver = 0,
      gold = 0,
    },
    updated = 1780148723,
    lastSeenWhere = "right here",
    key = "mutated silver wolf",
    killLocations = {
      ["Entrance To The Camp"] = 2,
      ["Sharondaerl Forest"] = 3,
    },
    lastScanLocation = "right here",
    aliases = {
      ["mutated silver wolf"] = true,
      wolf = true,
      ["silver wolf"] = true,
    },
    _lastXPSampleToken = 1779700129.156,
    lastKilledAt = 1779700129.156,
    lastSeenAt = 1780148900,
    _lastKillToken = 1779700129.156,
    roomsFound = {
      ["unknown room"] = 8,
      ["Sharondaerl Forest"] = 7,
    },
    killCount = 1,
    scan = {
      raw = "a mutated silver wolf, nearby to the north.",
      name = "a mutated silver wolf",
      key = "mutated silver wolf",
      display = "a mutated silver wolf",
      where = "the north.",
      updated = 1780148723,
      count = 4,
    },
    lastSeenArea = "unknown area",
    source = "scan",
    lastKilledRoomName = "Entrance To The Camp",
    name = "a mutated silver wolf",
    display = "a mutated silver wolf",
    lastSeenRoomName = "unknown room",
    lastKilledArea = "unknown area",
    xpTotal = 2898,
  },
  ["dwarven scout"] = {
    source = "scan",
    lastSeen = 1779700143,
    scan = {
      raw = "a dwarven scout, nearby to the southwest.",
      name = "a dwarven scout",
      count = 8,
      display = "a dwarven scout",
      updated = 1779700112,
      where = "the southwest.",
      key = "dwarven scout",
    },
    roomsFound = {
      ["Entrance To The Camp"] = 8,
      ["unknown room"] = 8,
      ["Higher Ground  "] = 8,
    },
    lastSeenAt = 1779700143,
    aliases = {
      ["dwarven scout"] = true,
      scout = true,
    },
    lastSeenArea = "unknown area",
    lastSeenWhere = "right here",
    name = "a dwarven scout",
    key = "dwarven scout",
    display = "a dwarven scout",
    lastSeenRoomName = "unknown room",
    updated = 1779700112,
    lastScanLocation = "right here",
  },
  hache = {
    source = "scan",
    lastSeen = 1780791192,
    aliases = {
      hache = true,
    },
    roomsFound = {
      ["Palace Courtyard"] = 7,
      ["Center of the Courtyard"] = 1,
      ["unknown room"] = 28,
    },
    lastSeenRoomName = "unknown room",
    scan = {
      raw = "Hache, right here.",
      name = "Hache",
      count = 1,
      display = "Hache",
      updated = 1780788207,
      where = "right here",
      key = "hache",
    },
    updated = 1780788207,
    lastSeenWhere = "right here",
    name = "Hache",
    key = "hache",
    display = "Hache",
    lastSeenAt = 1780791192,
    lastSeenArea = "unknown area",
    lastScanLocation = "right here",
  },
  andreyna = {
    source = "scan",
    lastSeen = 1780788754,
    aliases = {
      andreyna = true,
    },
    roomsFound = {
      ["unknown room"] = 20,
      ["Palace Courtyard"] = 5,
    },
    lastSeenRoomName = "unknown room",
    scan = {
      raw = "Andreyna, right here.",
      name = "Andreyna",
      count = 1,
      display = "Andreyna",
      updated = 1780788255,
      where = "right here",
      key = "andreyna",
    },
    updated = 1780788255,
    lastSeenWhere = "right here",
    name = "Andreyna",
    key = "andreyna",
    display = "Andreyna",
    lastSeenAt = 1780788754,
    lastSeenArea = "unknown area",
    lastScanLocation = "right here",
  },
  ["tinker gnome timekeeper"] = {
    dmg = "5d8 pierce",
    tactics = "berserk dodge trip",
    source = "creaturelore",
    magic = 1113,
    aliases = {
      ["tinker gnome timekeeper"] = true,
    },
    updated = 1779698230,
    race = "tinker gnome",
    loreSource = "learned",
    affects = "sanctuary haste",
    level = "50",
    damage = "5d8 pierce",
    key = "tinker gnome timekeeper",
    learnedAt = 1779698230,
    baseMana = 1113,
    baseHp = 4736,
    resist = "mental disease",
    name = "a tinker gnome timekeeper",
    lastUpdated = 1779698230,
    resistances = "mental disease",
    display = "a tinker gnome timekeeper",
    immune = "summon charm",
    immunities = "summon charm",
    commandKey = "'tinker gnome timekeeper'",
  },
  ["blue jay"] = {
    source = "scan",
    lastSeen = 1780698478,
    scan = {
      raw = "a blue jay, nearby to the west.",
      name = "a blue jay",
      key = "blue jay",
      display = "a blue jay",
      where = "the west.",
      updated = 1780698478,
      count = 2,
    },
    lastSeenArea = "unknown area",
    lastSeenRoomName = "unknown room",
    aliases = {
      jay = true,
      ["blue jay"] = true,
    },
    roomsFound = {
      ["Rolling forest"] = 1,
      ["The Hill-lands"] = 8,
      ["unknown room"] = 4,
    },
    lastSeenWhere = "right here",
    name = "a blue jay",
    key = "blue jay",
    display = "a blue jay",
    lastSeenAt = 1780698478,
    updated = 1780698478,
    lastScanLocation = "right here",
  },
  gardener = {
    source = "scan",
    lastSeen = 1780788169,
    aliases = {
      gardener = true,
    },
    roomsFound = {
      ["Palace Courtyard"] = 2,
      ["Center of the Courtyard"] = 2,
      ["unknown room"] = 4,
    },
    lastSeenRoomName = "unknown room",
    scan = {
      raw = "the gardener, right here.",
      name = "the gardener",
      count = 2,
      display = "the gardener",
      updated = 1780788169,
      where = "right here",
      key = "gardener",
    },
    updated = 1780788169,
    lastSeenWhere = "right here",
    name = "the gardener",
    key = "gardener",
    display = "the gardener",
    lastSeenAt = 1780788169,
    lastSeenArea = "unknown area",
    lastScanLocation = "right here",
  },
  terri = {
    source = "scan",
    lastSeen = 1780791192,
    scan = {
      raw = "Terri, right here.",
      name = "Terri",
      count = 1,
      display = "Terri",
      updated = 1780788422,
      where = "right here",
      key = "terri",
    },
    roomsFound = {
      Limbo = 3,
      ["Palace Courtyard"] = 5,
      ["unknown room"] = 20,
      ["AGL Betting Window"] = 2,
    },
    lastSeenRoomName = "unknown room",
    aliases = {
      terri = true,
    },
    lastSeenArea = "unknown area",
    lastSeenWhere = "right here",
    name = "Terri",
    key = "terri",
    display = "Terri",
    lastSeenAt = 1780791192,
    updated = 1780788422,
    lastScanLocation = "right here",
  },
  ["gnome greaser"] = {
    lastXP = 36,
    lastSeen = 1780152234,
    magic = 899,
    lastKilledArea = "unknown area",
    xpTotal = 86,
    key = "gnome greaser",
    resists = "mental disease",
    level = "45",
    killLocations = {
      ["Northeast end of the Clockworks"] = 3,
    },
    _lastKillToken = 1779694468.548,
    baseHp = 3138,
    lastSeenArea = "unknown area",
    name = "a gnome greaser",
    sex = "female",
    display = "a gnome greaser",
    lastSeenAt = 1780152234,
    source = "scan",
    lastSeenRoomName = "unknown room",
    resistances = "mental disease",
    alignmentText = "a good",
    hp = 3138,
    coins = {
      silver = 0,
      gold = 0,
    },
    updated = 1779686952,
    _lastXPSampleToken = 1779694982.447,
    lastSeenWhere = "right here",
    gold = 0,
    aliases = {
      ["gnome greaser"] = true,
      greaser = true,
    },
    xpSamples = 1,
    damage = "8d4 punch",
    lastScanLocation = "right here",
    silver = 0,
    damageType = "punch",
    lastKilledAt = 1779694468.548,
    drops = {
      ["grease-covered towel"] = 1,
    },
    lored = true,
    dmg = "8d4 punch",
    baseMana = 899,
    scan = {
      raw = "a gnome greaser, nearby to the southwest.",
      name = "a gnome greaser",
      count = 4,
      display = "a gnome greaser",
      updated = 1779693787,
      where = "the southwest.",
      key = "gnome greaser",
    },
    resist = "mental disease",
    avgXP = 86,
    lastKilledRoomName = "Northeast end of the Clockworks",
    rawLore = {
      [7] = "The base magically ability of this creature is 899.",
      [1] = "Creature: a gnome greaser Race: tinker gnome",
      [2] = "----------------------------------------------------------",
      [4] = "Their wealth appears to be 0 gold and 0 silver",
      [8] = "This creature is upon the cycle of training '45'",
      [9] = "This creature does 8d4 damage in a punch manner.",
      [5] = "They appear to be female.",
      [10] = "The creature has the following characteristics:",
      [3] = "a gnome greaser appears to be a good soul.",
      [6] = "The base health of this creature is 3138.",
      [12] = "",
      [11] = "Resistances: mental disease",
    },
    race = "tinker gnome",
    lastLore = 1779686952.438,
    killCount = 1,
    roomsFound = {
      ["Northeast end of the Clockworks"] = 241,
      ["Eastern end of the Clockworks"] = 90,
      ["unknown room"] = 306,
      ["The Docks"] = 16,
      ["Northern end of the Clockworks"] = 16,
    },
  },
  ["throughbred stallion"] = {
    dmg = "4d6 bite",
    lastSeen = 1780152234,
    rooms = {
      ["In the Main Gathering Room of the Fellowship Saloon"] = 3,
    },
    magic = 496,
    aliases = {
      ["throughbred stallion"] = true,
      stallion = true,
    },
    key = "throughbred stallion",
    affects = "charm",
    lastLore = 1779683625.491,
    baseHp = 905,
    roomsFound = {
      ["Temple Road"] = 1,
      ["Arkane's Temple"] = 48,
      ["On the Porch of the Fellowship Saloon"] = 16,
      ["Northern end of the Clockworks"] = 4,
      ["A Chainlink Platform in Fling-fall Cavern"] = 1,
      ["Northeast end of the Clockworks"] = 62,
      ["unknown room"] = 340,
      ["In the Main Gathering Room of the Fellowship Saloon"] = 9,
      ["An alleyway"] = 1,
      ["The Altar Room"] = 2,
      ["A Stone Slab Platform in Fling-fall Cavern"] = 2,
      ["Eastern end of the Clockworks"] = 24,
      ["Arkane's Shop of the Bizarre"] = 2,
      ["Philosophy Guild"] = 22,
      ["The High Priest of Arkane's Chamber"] = 4,
      ["A Grated Platform in Fling-fall Cavern"] = 4,
      ["Main Street"] = 5,
      ["Under Arkane Town Center"] = 1,
      ["The Docks"] = 4,
    },
    name = "a throughbred stallion",
    sex = "male",
    display = "a throughbred stallion",
    lastSeenRoomName = "unknown room",
    source = "scan",
    group = {
      raw = "[30 Mob] A throughbred stallion 100% hp 100% mana 100% mv",
      name = "A throughbred stallion",
      key = "throughbred stallion",
      class = "Mob",
      movePct = 100,
      level = 30,
      hpPct = 100,
      manaPct = 100,
    },
    hp = 905,
    updated = 1779683625,
    lastSeenWhere = "right here",
    gold = 0,
    damage = "4d6 bite",
    damageType = "bite",
    lored = true,
    baseMana = 496,
    scan = {
      raw = "a throughbred stallion, right here.",
      name = "a throughbred stallion",
      count = 1,
      display = "a throughbred stallion",
      updated = 1779692954,
      where = "right here",
      key = "throughbred stallion",
    },
    lastScanLocation = "right here",
    silver = 0,
    race = "horse",
    rawLore = {
      [7] = "The base magically ability of this creature is 496.",
      [1] = "Creature: a throughbred stallion Race: horse",
      [2] = "----------------------------------------------------------",
      [4] = "Their wealth appears to be 0 gold and 0 silver",
      [8] = "This creature is upon the cycle of training '30'",
      [9] = "This creature does 4d6 damage in a bite manner.",
      [5] = "They appear to be male.",
      [10] = "The creature has the following characteristics:",
      [3] = "a throughbred stallion appears to be a more neutral soul.",
      [6] = "The base health of this creature is 905.",
      [12] = "",
      [11] = "This creature is affected by charm",
    },
    level = "30",
    alignmentText = "a more neutral",
    lastSeenArea = "unknown area",
    lastSeenAt = 1780152234,
  },
  ["southern gate guard"] = {
    source = "scan",
    lastSeen = 1780149620,
    scan = {
      raw = "southern gate guard, right here.",
      name = "southern gate guard",
      count = 1,
      display = "southern gate guard",
      updated = 1780149620,
      where = "right here",
      key = "southern gate guard",
    },
    roomsFound = {
      ["Entrance to the Stronghold"] = 2,
      ["unknown room"] = 4,
    },
    lastSeenAt = 1780149620,
    aliases = {
      guard = true,
      ["southern gate guard"] = true,
      ["gate guard"] = true,
    },
    lastSeenArea = "unknown area",
    lastSeenWhere = "right here",
    name = "southern gate guard",
    key = "southern gate guard",
    display = "southern gate guard",
    lastSeenRoomName = "unknown room",
    updated = 1780149620,
    lastScanLocation = "right here",
  },
  ["sala'hudin"] = {
    source = "scan",
    lastSeen = 1780791192,
    aliases = {
      ["sala hudin"] = true,
      ["sala'hudin"] = true,
    },
    roomsFound = {
      ["Palace Courtyard"] = 7,
      ["Center of the Courtyard"] = 1,
      ["unknown room"] = 28,
    },
    lastSeenRoomName = "unknown room",
    scan = {
      raw = "Sala'hudin, right here.",
      name = "Sala'hudin",
      count = 1,
      display = "Sala'hudin",
      updated = 1780788207,
      where = "right here",
      key = "sala'hudin",
    },
    updated = 1780788207,
    lastSeenWhere = "right here",
    name = "Sala'hudin",
    key = "sala'hudin",
    display = "Sala'hudin",
    lastSeenAt = 1780791192,
    lastSeenArea = "unknown area",
    lastScanLocation = "right here",
  },
  ["dwarven cleric"] = {
    source = "scan",
    lastSeen = 1779700113,
    scan = {
      raw = "a dwarven cleric, nearby to the west.",
      name = "a dwarven cleric",
      count = 6,
      display = "a dwarven cleric",
      updated = 1779700112,
      where = "the west.",
      key = "dwarven cleric",
    },
    roomsFound = {
      ["unknown room"] = 4,
      ["Entrance To The Camp"] = 6,
    },
    lastSeenAt = 1779700113,
    aliases = {
      ["dwarven cleric"] = true,
      cleric = true,
    },
    lastSeenArea = "unknown area",
    lastSeenWhere = "right here",
    name = "a dwarven cleric",
    key = "dwarven cleric",
    display = "a dwarven cleric",
    lastSeenRoomName = "unknown room",
    updated = 1779700112,
    lastScanLocation = "right here",
  },
  cailene = {
    source = "scan",
    lastSeen = 1780791192,
    aliases = {
      cailene = true,
    },
    roomsFound = {
      ["Palace Courtyard"] = 7,
      ["Center of the Courtyard"] = 1,
      ["unknown room"] = 28,
    },
    lastSeenRoomName = "unknown room",
    scan = {
      raw = "Cailene, right here.",
      name = "Cailene",
      count = 1,
      display = "Cailene",
      updated = 1780788207,
      where = "right here",
      key = "cailene",
    },
    updated = 1780788207,
    lastSeenWhere = "right here",
    name = "Cailene",
    key = "cailene",
    display = "Cailene",
    lastSeenAt = 1780791192,
    lastSeenArea = "unknown area",
    lastScanLocation = "right here",
  },
  ["young blue gnome guard"] = {
    dmg = "8d4 slash",
    tactics = "assist_race",
    baseMana = 885,
    updated = 1779685489,
    name = "a young blue gnome guard",
    affects = "detect_invis detect_hidden",
    baseHp = 3153,
    aliases = {
      ["young blue gnome guard"] = true,
    },
    resist = "mental disease",
    race = "tinker gnome",
    key = "young blue gnome guard",
    resistances = "mental disease",
    display = "a young blue gnome guard",
    level = "45",
    magic = 885,
    damage = "8d4 slash",
  },
  ["dwarven pikeman"] = {
    source = "scan",
    lastSeen = 1779700113,
    scan = {
      raw = "a dwarven pikeman, nearby to the west.",
      name = "a dwarven pikeman",
      count = 6,
      display = "a dwarven pikeman",
      updated = 1779700112,
      where = "the west.",
      key = "dwarven pikeman",
    },
    roomsFound = {
      ["unknown room"] = 4,
      ["Entrance To The Camp"] = 6,
    },
    lastSeenAt = 1779700113,
    aliases = {
      pikeman = true,
      ["dwarven pikeman"] = true,
    },
    lastSeenArea = "unknown area",
    lastSeenWhere = "right here",
    name = "a dwarven pikeman",
    key = "dwarven pikeman",
    display = "a dwarven pikeman",
    lastSeenRoomName = "unknown room",
    updated = 1779700112,
    lastScanLocation = "right here",
  },
  ["wild elf hunter"] = {
    source = "scan",
    lastSeen = 1780701952,
    roomsFound = {
      ["The Hill-lands"] = 4,
      ["unknown room"] = 12,
      ["Rolling forest"] = 1,
      ["Inside the forest"] = 3,
      ["Dense trees"] = 1,
    },
    key = "wild elf hunter",
    lastSeenRoomName = "unknown room",
    aliases = {
      ["wild elf hunter"] = true,
      hunter = true,
      ["elf hunter"] = true,
    },
    updated = 1779700577,
    lastSeenWhere = "right here",
    name = "a wild elf hunter",
    scan = {
      raw = "a wild elf hunter, right here.",
      name = "a wild elf hunter",
      count = 1,
      display = "a wild elf hunter",
      updated = 1779700577,
      where = "right here",
      key = "wild elf hunter",
    },
    display = "a wild elf hunter",
    lastSeenAt = 1780701952,
    lastSeenArea = "unknown area",
    lastScanLocation = "right here",
  },
  ["beautiful white charger"] = {
    aliases = {
      ["beautiful white charger"] = true,
      ["white charger"] = true,
      charger = true,
    },
    source = "scan",
    lastSeen = 1780792807,
    group = {
      raw = "[51 Mob] A beautiful white charger 100% hp   0% mana 100% mv",
      key = "beautiful white charger",
      name = "A beautiful white charger",
      level = 51,
      hpPct = 100,
      class = "Mob",
      movePct = 100,
      manaPct = 0,
    },
    roomsFound = {
      ["Chamber of the High Priest of Althainia"] = 1,
      ["A Quiet bar in the Blue Gryphon"] = 1,
      ["Inside the forest"] = 3,
      ["Entrance to the Grunting Boar Inn"] = 1,
      ["The Hill-lands"] = 8,
      ["Market Square"] = 1,
      Limbo = 33,
      ["By the Temple Altar"] = 2,
      ["unknown room"] = 32,
      ["The Altar Room"] = 7,
      ["Northeast end of the Clockworks"] = 81,
      ["Common Room of the Blue Gryphon"] = 27,
      ["A Trail Around Shalonesti"] = 2,
      ["Dense trees"] = 1,
      ["The Temple Of The Gods"] = 2,
      ["Rolling forest"] = 1,
      ["Olyndros                     Chamber of the High Priest of Althainia"] = 1,
      ["The Temple Square"] = 4,
      ["ERROR: invalid line number"] = 4,
    },
    lastSeenRoomName = "unknown room",
    scan = {
      raw = "a beautiful white charger, right here.",
      name = "a beautiful white charger",
      count = 1,
      display = "a beautiful white charger",
      updated = 1779700551,
      where = "right here",
      key = "beautiful white charger",
    },
    updated = 1779700551,
    lastSeenWhere = "right here",
    name = "a beautiful white charger",
    key = "beautiful white charger",
    display = "a beautiful white charger",
    lastSeenAt = 1780792807,
    lastSeenArea = "unknown area",
    lastScanLocation = "right here",
  },
  ["small disfigured tree"] = {
    source = "scan",
    lastSeen = 1780148900,
    scan = {
      raw = "a small disfigured tree, right here.",
      name = "a small disfigured tree",
      count = 1,
      display = "a small disfigured tree",
      updated = 1779700378,
      where = "right here",
      key = "small disfigured tree",
    },
    roomsFound = {
      ["Sharondaerl Forest"] = 5,
      ["unknown room"] = 12,
      ["A Dim Forested Entrance"] = 1,
    },
    lastSeenAt = 1780148900,
    aliases = {
      ["disfigured tree"] = true,
      tree = true,
      ["small disfigured tree"] = true,
    },
    lastSeenArea = "unknown area",
    lastSeenWhere = "right here",
    name = "a small disfigured tree",
    key = "small disfigured tree",
    display = "a small disfigured tree",
    lastSeenRoomName = "unknown room",
    updated = 1779700378,
    lastScanLocation = "right here",
  },
  ["dwarven swordsman"] = {
    source = "scan",
    lastSeen = 1779700113,
    scan = {
      raw = "a dwarven swordsman, nearby to the west.",
      name = "a dwarven swordsman",
      count = 5,
      display = "a dwarven swordsman",
      updated = 1779700112,
      where = "the west.",
      key = "dwarven swordsman",
    },
    roomsFound = {
      ["unknown room"] = 4,
      ["Entrance To The Camp"] = 5,
    },
    lastSeenAt = 1779700113,
    aliases = {
      swordsman = true,
      ["dwarven swordsman"] = true,
    },
    lastSeenArea = "unknown area",
    lastSeenWhere = "right here",
    name = "a dwarven swordsman",
    key = "dwarven swordsman",
    display = "a dwarven swordsman",
    lastSeenRoomName = "unknown room",
    updated = 1779700112,
    lastScanLocation = "right here",
  },
  sofie = {
    source = "scan",
    lastSeen = 1780791192,
    updated = 1780788422,
    key = "sofie",
    lastSeenRoomName = "unknown room",
    aliases = {
      sofie = true,
    },
    roomsFound = {
      Limbo = 1,
      ["unknown room"] = 20,
      ["Palace Courtyard"] = 5,
    },
    lastSeenWhere = "right here",
    name = "Sofie",
    scan = {
      raw = "Sofie, right here.",
      name = "Sofie",
      count = 1,
      display = "Sofie",
      updated = 1780788422,
      where = "right here",
      key = "sofie",
    },
    display = "Sofie",
    lastSeenAt = 1780791192,
    lastSeenArea = "unknown area",
    lastScanLocation = "right here",
  },
  ["cobra snake"] = {
    source = "scan",
    lastSeen = 1780149394,
    aliases = {
      snake = true,
      ["cobra snake"] = true,
    },
    updated = 1780149312,
    lastSeenWhere = "right here",
    key = "cobra snake",
    killLocations = {
      ["Entrance to the Stronghold"] = 6,
    },
    lastScanLocation = "right here",
    lastKilledAt = 1780149277.956,
    drops = {
      ["silver coin"] = 17,
    },
    _lastKillToken = 1780149277.956,
    roomsFound = {
      ["Guillotine Road"] = 1,
      ["Entrance to the Stronghold"] = 8,
      ["unknown room"] = 16,
    },
    killCount = 1,
    scan = {
      raw = "a cobra snake, nearby to the west.",
      name = "a cobra snake",
      count = 2,
      display = "a cobra snake",
      updated = 1780149312,
      where = "the west.",
      key = "cobra snake",
    },
    lastSeenArea = "unknown area",
    coins = {
      silver = 0,
      gold = 0,
    },
    name = "a cobra snake",
    lastSeenRoomName = "unknown room",
    display = "a cobra snake",
    lastSeenAt = 1780149394,
    lastKilledRoomName = "Entrance to the Stronghold",
    lastKilledArea = "unknown area",
  },
  ["wild elf bandit"] = {
    source = "scan",
    lastSeen = 1780698478,
    scan = {
      raw = "a wild elf bandit, right here.",
      name = "a wild elf bandit",
      key = "wild elf bandit",
      display = "a wild elf bandit",
      where = "right here",
      updated = 1780698478,
      count = 1,
    },
    lastSeenArea = "unknown area",
    lastSeenRoomName = "unknown room",
    aliases = {
      ["wild elf bandit"] = true,
      ["elf bandit"] = true,
      bandit = true,
    },
    roomsFound = {
      ["unknown room"] = 4,
      ["Northeast end of the Clockworks"] = 2,
      ["Inside the forest"] = 2,
      ["The Hill-lands"] = 1,
    },
    lastSeenWhere = "right here",
    name = "a wild elf bandit",
    key = "wild elf bandit",
    display = "a wild elf bandit",
    lastSeenAt = 1780698478,
    updated = 1780698478,
    lastScanLocation = "right here",
  },
  ["gnome architect"] = {
    lastXP = 118,
    tactics = "dodge",
    lastSeen = 1780152234,
    xpSamples = 1,
    aliases = {
      ["gnome architect"] = true,
      architect = true,
    },
    xpTotal = 118,
    key = "gnome architect",
    resists = "mental disease",
    level = "48",
    killLocations = {
      ["Northeast end of the Clockworks"] = 2,
    },
    _lastKillToken = 1779842112.924,
    baseHp = 3886,
    roomsFound = {
      ["Northeast end of the Clockworks"] = 247,
      ["Eastern end of the Clockworks"] = 96,
      ["unknown room"] = 330,
      ["The Docks"] = 16,
      ["Northern end of the Clockworks"] = 15,
    },
    name = "a gnome architect",
    resistances = "mental disease",
    display = "a gnome architect",
    lastSeenRoomName = "unknown room",
    avgXP = 118,
    killCount = 1,
    alignmentText = "a good",
    hp = 3886,
    coins = {
      silver = 0,
      gold = 0,
    },
    updated = 1779686139,
    _lastXPSampleToken = 1779842112.924,
    race = "tinker gnome",
    gold = 0,
    magic = 1082,
    source = "scan",
    lastKilledArea = "unknown area",
    damage = "6d6 punch",
    dmg = "6d6 punch",
    damageType = "punch",
    lastKilledAt = 1779842112.924,
    lastSeenAt = 1780152234,
    lastSeenArea = "unknown area",
    silver = 0,
    baseMana = 1082,
    scan = {
      raw = "a gnome architect, nearby to the southwest.",
      name = "a gnome architect",
      count = 4,
      display = "a gnome architect",
      updated = 1779693787,
      where = "the southwest.",
      key = "gnome architect",
    },
    resist = "mental disease",
    lored = true,
    lastKilledRoomName = "Northeast end of the Clockworks",
    rawLore = {
      [13] = "",
      [7] = "The base magically ability of this creature is 1082.",
      [1] = "Creature: a gnome architect Race: tinker gnome",
      [2] = "----------------------------------------------------------",
      [4] = "Their wealth appears to be 0 gold and 0 silver",
      [8] = "This creature is upon the cycle of training '48'",
      [9] = "This creature does 6d6 damage in a punch manner.",
      [5] = "They appear to be female.",
      [10] = "The creature has the following characteristics:",
      [3] = "a gnome architect appears to be a good soul.",
      [6] = "The base health of this creature is 3886.",
      [12] = "Resistances: mental disease",
      [11] = "Offensive Tactics:dodge",
    },
    lastSeenWhere = "right here",
    lastScanLocation = "right here",
    lastLore = 1779686139.618,
    sex = "female",
  },
  ["dwarven assassin"] = {
    source = "scan",
    lastSeen = 1779700143,
    scan = {
      raw = "a dwarven assassin, nearby to the west.",
      name = "a dwarven assassin",
      count = 6,
      display = "a dwarven assassin",
      updated = 1779700143,
      where = "the west.",
      key = "dwarven assassin",
    },
    roomsFound = {
      ["Entrance To The Camp"] = 2,
      ["unknown room"] = 4,
      ["Higher Ground  "] = 6,
    },
    lastSeenAt = 1779700143,
    aliases = {
      assassin = true,
      ["dwarven assassin"] = true,
    },
    lastSeenArea = "unknown area",
    lastSeenWhere = "right here",
    name = "a dwarven assassin",
    key = "dwarven assassin",
    display = "a dwarven assassin",
    lastSeenRoomName = "unknown room",
    updated = 1779700143,
    lastScanLocation = "right here",
  },
  ["dwarven crusader"] = {
    source = "scan",
    lastSeen = 1779700143,
    scan = {
      raw = "a dwarven crusader, nearby to the west.",
      name = "a dwarven crusader",
      count = 6,
      display = "a dwarven crusader",
      updated = 1779700143,
      where = "the west.",
      key = "dwarven crusader",
    },
    roomsFound = {
      ["Entrance To The Camp"] = 2,
      ["unknown room"] = 4,
      ["Higher Ground  "] = 6,
    },
    lastSeenAt = 1779700143,
    aliases = {
      crusader = true,
      ["dwarven crusader"] = true,
    },
    lastSeenArea = "unknown area",
    lastSeenWhere = "right here",
    name = "a dwarven crusader",
    key = "dwarven crusader",
    display = "a dwarven crusader",
    lastSeenRoomName = "unknown room",
    updated = 1779700143,
    lastScanLocation = "right here",
  },
  ["ivory opinicus"] = {
    source = "scan",
    lastSeen = 1780149609,
    scan = {
      raw = "an ivory opinicus, nearby to the west.",
      name = "an ivory opinicus",
      count = 7,
      display = "an ivory opinicus",
      updated = 1780149394,
      where = "the west.",
      key = "ivory opinicus",
    },
    roomsFound = {
      ["Entrance to the Stronghold"] = 35,
      ["unknown room"] = 24,
    },
    lastSeenAt = 1780149609,
    aliases = {
      ["ivory opinicus"] = true,
      opinicus = true,
    },
    lastSeenArea = "unknown area",
    lastSeenWhere = "right here",
    name = "an ivory opinicus",
    key = "ivory opinicus",
    display = "an ivory opinicus",
    lastSeenRoomName = "unknown room",
    updated = 1780149394,
    lastScanLocation = "right here",
  },
  ["earth elemental"] = {
    source = "scan",
    lastSeen = 1779730933,
    scan = {
      raw = "an earth elemental, right here.",
      name = "an earth elemental",
      key = "earth elemental",
      display = "an earth elemental",
      where = "right here",
      updated = 1779730933,
      count = 1,
    },
    roomsFound = {
      ["City street"] = 3,
      ["unknown room"] = 4,
    },
    lastSeenAt = 1779730933,
    aliases = {
      elemental = true,
      ["earth elemental"] = true,
    },
    lastSeenArea = "unknown area",
    lastSeenWhere = "right here",
    name = "an earth elemental",
    key = "earth elemental",
    display = "an earth elemental",
    lastSeenRoomName = "unknown room",
    updated = 1779730933,
    lastScanLocation = "right here",
  },
  ["gnome philosophy instructor"] = {
    dmg = "6d7 pierce",
    source = "creaturelore",
    learnedAt = 1779687932,
    aliases = {
      ["gnome philosophy instructor"] = true,
    },
    updated = 1779687932,
    race = "tinker gnome",
    loreSource = "learned",
    commandKey = "'gnome philosophy instructor'",
    level = "53",
    damage = "6d7 pierce",
    baseMana = 1306,
    resist = "mental disease",
    baseHp = 6298,
    lastUpdated = 1779687932,
    resistances = "mental disease",
    display = "a gnome philosophy instructor",
    magic = 1306,
    name = "a gnome philosophy instructor",
    key = "gnome philosophy instructor",
  },
  ["horribly disfigured blue jay"] = {
    source = "scan",
    lastSeen = 1780148900,
    scan = {
      raw = "a horribly disfigured blue jay, nearby to the north.",
      name = "a horribly disfigured blue jay",
      key = "horribly disfigured blue jay",
      display = "a horribly disfigured blue jay",
      where = "the north.",
      updated = 1780148723,
      count = 4,
    },
    lastSeenArea = "unknown area",
    lastSeenAt = 1780148900,
    aliases = {
      ["horribly disfigured blue jay"] = true,
      ["blue jay"] = true,
      jay = true,
      ["disfigured blue jay"] = true,
    },
    roomsFound = {
      ["unknown room"] = 8,
      ["Sharondaerl Forest"] = 7,
    },
    lastSeenWhere = "right here",
    name = "a horribly disfigured blue jay",
    key = "horribly disfigured blue jay",
    display = "a horribly disfigured blue jay",
    lastSeenRoomName = "unknown room",
    updated = 1780148723,
    lastScanLocation = "right here",
  },
  ["tinker gnome janitor"] = {
    dmg = "5d8 pound",
    source = "creaturelore",
    learnedAt = 1779688267,
    aliases = {
      ["tinker gnome janitor"] = true,
    },
    updated = 1779688267,
    race = "tinker gnome",
    loreSource = "learned",
    commandKey = "'tinker gnome janitor'",
    level = "51",
    damage = "5d8 pound",
    baseMana = 1200,
    resist = "mental disease",
    lastUpdated = 1779688267,
    name = "a tinker gnome janitor",
    resistances = "mental disease",
    display = "a tinker gnome janitor",
    magic = 1200,
    baseHp = 5281,
    key = "tinker gnome janitor",
  },
  meki = {
    source = "scan",
    lastSeen = 1780791192,
    updated = 1780788207,
    key = "meki",
    lastSeenRoomName = "unknown room",
    aliases = {
      meki = true,
    },
    roomsFound = {
      ["Center of the Courtyard"] = 1,
      ["Palace Courtyard"] = 7,
      ["Inside the West Gate of New Thalos"] = 1,
      ["unknown room"] = 28,
    },
    lastSeenWhere = "right here",
    name = "Meki",
    scan = {
      raw = "Meki, right here.",
      name = "Meki",
      count = 1,
      display = "Meki",
      updated = 1780788207,
      where = "right here",
      key = "meki",
    },
    display = "Meki",
    lastSeenAt = 1780791192,
    lastSeenArea = "unknown area",
    lastScanLocation = "right here",
  },
}
