return {{[ [[gnome factory worker]] ] = {2},[ [[gnome greaser]] ] = {3},[ [[gnome machinist]] ] = {4},[ [[gnome architect]] ] = {5},},
{[ [[damageType]] ] = [[slash]],[ [[silver]] ] = 0,[ [[lastLore]] ] = 1783821093,[ [[hp]] ] = 3395,[ [[key]] ] = [[gnome factory worker]],[ [[trainingCycle]] ] = 46,[ [[race]] ] = [[tinker gnome]],[ [[name]] ] = [[a gnome factory worker]],[ [[gold]] ] = 0,[ [[resists]] ] = {6},[ [[alignmentText]] ] = [[good]],[ [[magic]] ] = 952,[ [[damage]] ] = [[6d6]],},
{[ [[damageType]] ] = [[punch]],[ [[silver]] ] = 0,[ [[lastLore]] ] = 1783821595,[ [[hp]] ] = 3141,[ [[key]] ] = [[gnome greaser]],[ [[trainingCycle]] ] = 45,[ [[race]] ] = [[tinker gnome]],[ [[name]] ] = [[a gnome greaser]],[ [[gold]] ] = 0,[ [[resists]] ] = {7},[ [[alignmentText]] ] = [[good]],[ [[magic]] ] = 862,[ [[damage]] ] = [[8d4]],},
{[ [[damageType]] ] = [[pierce]],[ [[silver]] ] = 0,[ [[lastLore]] ] = 1783821168,[ [[key]] ] = [[gnome machinist]],[ [[trainingCycle]] ] = 47,[ [[hp]] ] = 3665,[ [[tactics]] ] = {8},[ [[affects]] ] = {9},[ [[race]] ] = [[tinker gnome]],[ [[name]] ] = [[a gnome machinist]],[ [[gold]] ] = 0,[ [[resists]] ] = {10},[ [[alignmentText]] ] = [[good]],[ [[magic]] ] = 976,[ [[damage]] ] = [[6d6]],},
{[ [[damageType]] ] = [[punch]],[ [[silver]] ] = 0,[ [[lastLore]] ] = 1783821653,[ [[key]] ] = [[gnome architect]],[ [[hp]] ] = 3912,[ [[trainingCycle]] ] = 48,[ [[tactics]] ] = {11},[ [[race]] ] = [[tinker gnome]],[ [[name]] ] = [[a gnome architect]],[ [[gold]] ] = 0,[ [[resists]] ] = {12},[ [[alignmentText]] ] = [[good]],[ [[magic]] ] = 1027,[ [[damage]] ] = [[6d6]],},
{[1] = [[mental]],[2] = [[disease]],},
{[1] = [[mental]],[2] = [[disease]],},
{[1] = [[bash]],[2] = [[trip]],},
{[1] = [[haste]],},
{[1] = [[mental]],[2] = [[disease]],},
{[1] = [[dodge]],},
{[1] = [[mental]],[2] = [[disease]],},
}