return {{[ [[gnome greaser]] ] = {2},[ [[gnome factory worker]] ] = {3},[ [[gnome machinist]] ] = {4},[ [[gnome architect]] ] = {5},},
{[ [[damageType]] ] = [[punch]],[ [[silver]] ] = 0,[ [[lastLore]] ] = 1783824674,[ [[hp]] ] = 3128,[ [[key]] ] = [[gnome greaser]],[ [[trainingCycle]] ] = 45,[ [[race]] ] = [[tinker gnome]],[ [[name]] ] = [[a gnome greaser]],[ [[gold]] ] = 0,[ [[resists]] ] = {6},[ [[alignmentText]] ] = [[good]],[ [[magic]] ] = 829,[ [[damage]] ] = [[8d4]],},
{[ [[damageType]] ] = [[pierce]],[ [[silver]] ] = 0,[ [[trainingCycle]] ] = 46,[ [[hp]] ] = 3397,[ [[name]] ] = [[a gnome factory worker]],[ [[lastLore]] ] = 1783823729,[ [[race]] ] = [[tinker gnome]],[ [[key]] ] = [[gnome factory worker]],[ [[gold]] ] = 0,[ [[resists]] ] = {7},[ [[alignmentText]] ] = [[good]],[ [[magic]] ] = 976,[ [[damage]] ] = [[6d6]],},
{[ [[damageType]] ] = [[pound]],[ [[silver]] ] = 0,[ [[lastLore]] ] = 1783824683,[ [[key]] ] = [[gnome machinist]],[ [[trainingCycle]] ] = 47,[ [[hp]] ] = 3628,[ [[tactics]] ] = {8},[ [[affects]] ] = {9},[ [[race]] ] = [[tinker gnome]],[ [[name]] ] = [[a gnome machinist]],[ [[gold]] ] = 0,[ [[resists]] ] = {10},[ [[alignmentText]] ] = [[good]],[ [[magic]] ] = 1011,[ [[damage]] ] = [[6d6]],},
{[ [[damageType]] ] = [[punch]],[ [[silver]] ] = 0,[ [[lastLore]] ] = 1783824696,[ [[key]] ] = [[gnome architect]],[ [[hp]] ] = 3892,[ [[trainingCycle]] ] = 48,[ [[tactics]] ] = {11},[ [[race]] ] = [[tinker gnome]],[ [[name]] ] = [[a gnome architect]],[ [[gold]] ] = 0,[ [[resists]] ] = {12},[ [[alignmentText]] ] = [[good]],[ [[magic]] ] = 1063,[ [[damage]] ] = [[6d6]],},
{[1] = [[mental]],[2] = [[disease]],},
{[1] = [[mental]],[2] = [[disease]],},
{[1] = [[bash]],[2] = [[trip]],},
{[1] = [[haste]],},
{[1] = [[mental]],[2] = [[disease]],},
{[1] = [[dodge]],},
{[1] = [[mental]],[2] = [[disease]],},
}