return {{[ [[gnome machinist]] ] = {2},[ [[very large bind stone]] ] = {3},[ [[tinker gnome timekeeper]] ] = {4},[ [[blue crystal falcon]] ] = {5},[ [[gnome greaser]] ] = {6},[ [[forest hen]] ] = {7},[ [[boar]] ] = {8},[ [[green crystal beetle]] ] = {9},[ [[statue of siccara]] ] = {10},[ [[iron-cast cannonball is rolling around]] ] = {11},[ [[crystal gopher]] ] = {12},[ [[crystal scarecrow]] ] = {13},[ [[small prickly weed]] ] = {14},[ [[arkane gateguard]] ] = {15},[ [[high priest of arkane]] ] = {16},[ [[centaur filly]] ] = {17},[ [[red crystalline mantis]] ] = {18},[ [[centaur ranger]] ] = {19},[ [[gnome]] ] = {20},[ [[gnome architect]] ] = {21},[ [[gnome factory worker]] ] = {22},[ [[wild bear]] ] = {23},[ [[yellow crystal centipede]] ] = {24},[ [[ornery centaur warrior]] ] = {25},[ [[arkane cityguard]] ] = {26},[ [[yonng centaur polo player]] ] = {27},[ [[statue of siccara, goddess of healing,]] ] = {28},[ [[gnome with a large paint brush and a can of grease]] ] = {29},},
{[ [[hp]] ] = 3628,[ [[damageType]] ] = [[pound]],[ [[silver]] ] = 0,[ [[lastSeen]] ] = 1783886850,[ [[magic]] ] = 1011,[ [[lastLore]] ] = 1783824683,[ [[trainingCycle]] ] = 47,[ [[key]] ] = [[gnome machinist]],[ [[affects]] ] = {30},[ [[race]] ] = [[tinker gnome]],[ [[name]] ] = [[a gnome machinist]],[ [[gold]] ] = 0,[ [[resists]] ] = {31},[ [[alignmentText]] ] = [[good]],[ [[tactics]] ] = {32},[ [[damage]] ] = [[6d6]],},
{[ [[firstSeen]] ] = 1783887767,[ [[name]] ] = [[A very large bind stone]],[ [[key]] ] = [[very large bind stone]],[ [[lastSeen]] ] = 1783887767,},
{[ [[firstSeen]] ] = 1783885512,[ [[name]] ] = [[a tinker gnome timekeeper]],[ [[key]] ] = [[tinker gnome timekeeper]],[ [[lastSeen]] ] = 1783886850,},
{[ [[firstSeen]] ] = 1783891361,[ [[name]] ] = [[a blue crystal falcon]],[ [[key]] ] = [[blue crystal falcon]],[ [[lastSeen]] ] = 1783891361,},
{[ [[damageType]] ] = [[punch]],[ [[silver]] ] = 0,[ [[lastSeen]] ] = 1783886850,[ [[hp]] ] = 3128,[ [[trainingCycle]] ] = 45,[ [[key]] ] = [[gnome greaser]],[ [[lastLore]] ] = 1783824674,[ [[race]] ] = [[tinker gnome]],[ [[name]] ] = [[a gnome greaser]],[ [[gold]] ] = 0,[ [[resists]] ] = {33},[ [[alignmentText]] ] = [[good]],[ [[magic]] ] = 829,[ [[damage]] ] = [[8d4]],},
{[ [[damageType]] ] = [[peck]],[ [[silver]] ] = 0,[ [[lastSeen]] ] = 1783887774,[ [[hp]] ] = 41,[ [[trainingCycle]] ] = 3,[ [[key]] ] = [[forest hen]],[ [[lastLore]] ] = 1783887777,[ [[race]] ] = [[landbird]],[ [[name]] ] = [[a forest hen]],[ [[gold]] ] = 0,[ [[firstSeen]] ] = 1783887774,[ [[alignmentText]] ] = [[neutral]],[ [[magic]] ] = 27,[ [[damage]] ] = [[1d6]],},
{[ [[tactics]] ] = {34},[ [[silver]] ] = 0,[ [[lastSeen]] ] = 1783887800,[ [[hp]] ] = 576,[ [[magic]] ] = 101,[ [[trainingCycle]] ] = 25,[ [[lastLore]] ] = 1783887805,[ [[key]] ] = [[boar]],[ [[race]] ] = [[pig]],[ [[name]] ] = [[a boar]],[ [[gold]] ] = 0,[ [[firstSeen]] ] = 1783887800,[ [[alignmentText]] ] = [[evil]],[ [[damageType]] ] = [[slash]],[ [[damage]] ] = [[2d10]],},
{[ [[firstSeen]] ] = 1783891361,[ [[name]] ] = [[a green crystal beetle]],[ [[key]] ] = [[green crystal beetle]],[ [[lastSeen]] ] = 1783891361,},
{[ [[damageType]] ] = [[pound]],[ [[silver]] ] = 0,[ [[lastSeen]] ] = 1783887828,[ [[immunities]] ] = {35},[ [[magic]] ] = 4000,[ [[trainingCycle]] ] = 55,[ [[lastLore]] ] = 1783887833,[ [[key]] ] = [[statue of siccara]],[ [[race]] ] = [[unique]],[ [[name]] ] = [[a statue of Siccara]],[ [[gold]] ] = 0,[ [[firstSeen]] ] = 1783887828,[ [[alignmentText]] ] = [[neutral]],[ [[hp]] ] = 10000,[ [[damage]] ] = [[1d1]],},
{[ [[firstSeen]] ] = 1783887767,[ [[name]] ] = [[An iron-cast cannonball is rolling around]],[ [[key]] ] = [[iron-cast cannonball is rolling around]],[ [[lastSeen]] ] = 1783887767,},
{[ [[firstSeen]] ] = 1783891361,[ [[name]] ] = [[a crystal gopher]],[ [[key]] ] = [[crystal gopher]],[ [[lastSeen]] ] = 1783891361,},
{[ [[damageType]] ] = [[slash]],[ [[silver]] ] = 0,[ [[lastSeen]] ] = 1783891361,[ [[trainingCycle]] ] = 10,[ [[hp]] ] = 225,[ [[name]] ] = [[a crystal scarecrow]],[ [[lastLore]] ] = 1783890285,[ [[race]] ] = [[unique]],[ [[key]] ] = [[crystal scarecrow]],[ [[gold]] ] = 0,[ [[firstSeen]] ] = 1783890280,[ [[alignmentText]] ] = [[good]],[ [[magic]] ] = 169,[ [[damage]] ] = [[2d6]],},
{[ [[tactics]] ] = {36},[ [[silver]] ] = 0,[ [[lastSeen]] ] = 1783890239,[ [[hp]] ] = 167,[ [[magic]] ] = 125,[ [[trainingCycle]] ] = 12,[ [[lastLore]] ] = 1783890255,[ [[key]] ] = [[small prickly weed]],[ [[race]] ] = [[plant]],[ [[name]] ] = [[a small prickly weed]],[ [[gold]] ] = 0,[ [[firstSeen]] ] = 1783887847,[ [[alignmentText]] ] = [[good]],[ [[damageType]] ] = [[pound]],[ [[damage]] ] = [[1d10]],},
{[ [[tactics]] ] = {37},[ [[silver]] ] = 0,[ [[lastSeen]] ] = 1783887710,[ [[magic]] ] = 515,[ [[race]] ] = [[human]],[ [[key]] ] = [[arkane gateguard]],[ [[gold]] ] = 0,[ [[alignmentText]] ] = [[neutral]],[ [[damage]] ] = [[5d4]],[ [[damageType]] ] = [[pierce]],[ [[immunities]] ] = {38},[ [[lastLore]] ] = 1783887716,[ [[name]] ] = [[an Arkane gateguard]],[ [[trainingCycle]] ] = 45,[ [[firstSeen]] ] = 1783887692,[ [[affects]] ] = {39},[ [[resists]] ] = {40},[ [[hp]] ] = 4000,},
{[ [[immunities]] ] = {41},[ [[damageType]] ] = [[slash]],[ [[silver]] ] = 0,[ [[lastSeen]] ] = 1783887677,[ [[magic]] ] = 0,[ [[lastLore]] ] = 1783887665,[ [[trainingCycle]] ] = 60,[ [[key]] ] = [[high priest of arkane]],[ [[affects]] ] = {42},[ [[race]] ] = [[human]],[ [[name]] ] = [[The High Priest of Arkane]],[ [[gold]] ] = 0,[ [[firstSeen]] ] = 1783887651,[ [[alignmentText]] ] = [[neutral]],[ [[hp]] ] = 10193,[ [[damage]] ] = [[0d0]],},
{[ [[damageType]] ] = [[slash]],[ [[silver]] ] = 0,[ [[lastSeen]] ] = 1783887931,[ [[magic]] ] = 0,[ [[key]] ] = [[centaur filly]],[ [[trainingCycle]] ] = 15,[ [[lastLore]] ] = 1783887934,[ [[resists]] ] = {43},[ [[race]] ] = [[horse]],[ [[name]] ] = [[a centaur filly]],[ [[gold]] ] = 0,[ [[firstSeen]] ] = 1783887878,[ [[alignmentText]] ] = [[good]],[ [[hp]] ] = 218,[ [[damage]] ] = [[2d5]],},
{[ [[firstSeen]] ] = 1783891361,[ [[name]] ] = [[a red crystalline mantis]],[ [[key]] ] = [[red crystalline mantis]],[ [[lastSeen]] ] = 1783891361,},
{[ [[damageType]] ] = [[slash]],[ [[silver]] ] = 0,[ [[lastSeen]] ] = 1783887931,[ [[magic]] ] = 0,[ [[key]] ] = [[centaur ranger]],[ [[trainingCycle]] ] = 15,[ [[lastLore]] ] = 1783887884,[ [[resists]] ] = {44},[ [[race]] ] = [[horse]],[ [[name]] ] = [[a centaur ranger]],[ [[gold]] ] = 0,[ [[firstSeen]] ] = 1783887878,[ [[alignmentText]] ] = [[good]],[ [[hp]] ] = 230,[ [[damage]] ] = [[3d5]],},
{[ [[firstSeen]] ] = 1783885483,[ [[name]] ] = [[A gnome]],[ [[key]] ] = [[gnome]],[ [[lastSeen]] ] = 1783886091,},
{[ [[tactics]] ] = {45},[ [[silver]] ] = 0,[ [[lastSeen]] ] = 1783886850,[ [[trainingCycle]] ] = 48,[ [[magic]] ] = 1063,[ [[hp]] ] = 3892,[ [[lastLore]] ] = 1783824696,[ [[key]] ] = [[gnome architect]],[ [[race]] ] = [[tinker gnome]],[ [[name]] ] = [[a gnome architect]],[ [[gold]] ] = 0,[ [[resists]] ] = {46},[ [[alignmentText]] ] = [[good]],[ [[damageType]] ] = [[punch]],[ [[damage]] ] = [[6d6]],},
{[ [[damageType]] ] = [[pound]],[ [[silver]] ] = 0,[ [[lastSeen]] ] = 1783886850,[ [[trainingCycle]] ] = 46,[ [[hp]] ] = 3372,[ [[name]] ] = [[a gnome factory worker]],[ [[lastLore]] ] = 1783886853,[ [[race]] ] = [[tinker gnome]],[ [[key]] ] = [[gnome factory worker]],[ [[gold]] ] = 0,[ [[resists]] ] = {47},[ [[alignmentText]] ] = [[good]],[ [[magic]] ] = 924,[ [[damage]] ] = [[6d6]],},
{[ [[tactics]] ] = {48},[ [[silver]] ] = 0,[ [[lastSeen]] ] = 1783886850,[ [[hp]] ] = 960,[ [[race]] ] = [[bear]],[ [[key]] ] = [[wild bear]],[ [[gold]] ] = 0,[ [[alignmentText]] ] = [[neutral]],[ [[damage]] ] = [[5d10]],[ [[damageType]] ] = [[pound]],[ [[immunities]] ] = {49},[ [[lastLore]] ] = 1783885575,[ [[name]] ] = [[a wild bear]],[ [[trainingCycle]] ] = 51,[ [[firstSeen]] ] = 1783885567,[ [[affects]] ] = {50},[ [[resists]] ] = {51},[ [[magic]] ] = 102,},
{[ [[firstSeen]] ] = 1783891361,[ [[name]] ] = [[a yellow crystal centipede]],[ [[key]] ] = [[yellow crystal centipede]],[ [[lastSeen]] ] = 1783891361,},
{[ [[firstSeen]] ] = 1783887910,[ [[name]] ] = [[an ornery centaur warrior]],[ [[key]] ] = [[ornery centaur warrior]],[ [[lastSeen]] ] = 1783887910,},
{[ [[tactics]] ] = {52},[ [[silver]] ] = 0,[ [[lastSeen]] ] = 1783887753,[ [[magic]] ] = 520,[ [[race]] ] = [[human]],[ [[key]] ] = [[arkane cityguard]],[ [[gold]] ] = 0,[ [[alignmentText]] ] = [[neutral]],[ [[damage]] ] = [[5d4]],[ [[damageType]] ] = [[pound]],[ [[immunities]] ] = {53},[ [[lastLore]] ] = 1783887701,[ [[name]] ] = [[an Arkane cityguard]],[ [[trainingCycle]] ] = 45,[ [[firstSeen]] ] = 1783887694,[ [[affects]] ] = {54},[ [[resists]] ] = {55},[ [[hp]] ] = 4000,},
{[ [[damageType]] ] = [[pound]],[ [[silver]] ] = 0,[ [[lastSeen]] ] = 1783887931,[ [[magic]] ] = 0,[ [[key]] ] = [[yonng centaur polo player]],[ [[trainingCycle]] ] = 17,[ [[lastLore]] ] = 1783887919,[ [[resists]] ] = {56},[ [[race]] ] = [[horse]],[ [[name]] ] = [[a yonng centaur polo player]],[ [[gold]] ] = 0,[ [[firstSeen]] ] = 1783887910,[ [[alignmentText]] ] = [[good]],[ [[hp]] ] = 236,[ [[damage]] ] = [[4d5]],},
{[ [[firstSeen]] ] = 1783887826,[ [[name]] ] = [[A statue of Siccara, Goddess of Healing,]],[ [[key]] ] = [[statue of siccara, goddess of healing,]],[ [[lastSeen]] ] = 1783887826,},
{[ [[firstSeen]] ] = 1783885483,[ [[name]] ] = [[A gnome with a large paint brush and a can of grease]],[ [[key]] ] = [[gnome with a large paint brush and a can of grease]],[ [[lastSeen]] ] = 1783886091,},
{[1] = [[haste]],},
{[1] = [[mental]],[2] = [[disease]],},
{[1] = [[bash]],[2] = [[trip]],},
{[1] = [[mental]],[2] = [[disease]],},
{[1] = [[bash]],[2] = [[dodge]],[3] = [[fast]],},
{[1] = [[summon]],[2] = [[poison]],[3] = [[disease]],[4] = [[tornado]],},
{[1] = [[bash]],[2] = [[trip]],},
{[1] = [[area]],[2] = [[attack]],[3] = [[bash]],[4] = [[berserk]],[5] = [[disarm]],[6] = [[dodge]],[7] = [[fast]],[8] = [[kick]],[9] = [[parry]],[10] = [[rescue]],[11] = [[trip]],[12] = [[crush]],[13] = [[assist_guard]],},
{[1] = [[summon]],[2] = [[charm]],[3] = [[mental]],},
{[1] = [[detect_evil]],[2] = [[infrared]],[3] = [[haste]],[4] = [[dark]],[5] = [[vision]],},
{[1] = [[magic]],[2] = [[weapon]],[3] = [[fire]],[4] = [[cold]],},
{[1] = [[summon]],[2] = [[charm]],[3] = [[magic]],[4] = [[weapon]],[5] = [[disease]],},
{[1] = [[sanctuary]],},
{[1] = [[blunt]],},
{[1] = [[blunt]],},
{[1] = [[dodge]],},
{[1] = [[mental]],[2] = [[disease]],},
{[1] = [[mental]],[2] = [[disease]],},
{[1] = [[bash]],[2] = [[berserk]],[3] = [[disarm]],[4] = [[dodge]],[5] = [[fast]],[6] = [[rescue]],[7] = [[crush]],},
{[1] = [[summon]],[2] = [[charm]],},
{[1] = [[charm]],[2] = [[dark]],[3] = [[vision]],},
{[1] = [[blunt]],[2] = [[cold]],},
{[1] = [[area]],[2] = [[attack]],[3] = [[bash]],[4] = [[berserk]],[5] = [[disarm]],[6] = [[dodge]],[7] = [[fast]],[8] = [[kick]],[9] = [[parry]],[10] = [[rescue]],[11] = [[trip]],[12] = [[crush]],[13] = [[assist_guard]],},
{[1] = [[summon]],[2] = [[charm]],[3] = [[mental]],},
{[1] = [[detect_evil]],[2] = [[infrared]],[3] = [[haste]],[4] = [[dark]],[5] = [[vision]],},
{[1] = [[magic]],[2] = [[weapon]],[3] = [[fire]],[4] = [[cold]],},
{[1] = [[blunt]],},
}